<?php
/**
 * Copyright © Soft Commerce Ltd. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \SoftCommerce\ProfileSchedule\Block\Adminhtml\Edit\Popup $block */
?>

<script>
    (function ($) {
        let response = <?= /* @noEscape */ $block->getResponseJson() ?>;
        $('[data-role=profile-schedule]').trigger('add', response.schedule);
        $('#create_new_schedule').modal('closeModal');
    })(window.parent.jQuery);
</script>
