name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "1.3.5"
          tag_name: 1.3.5
          body: "1.3.5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
